// This file is auto-generated by @hey-api/openapi-ts

export const AdminAgreementMetricSchema = {
    properties: {
        dimension: {
            type: 'string',
            title: 'Dimension'
        },
        alpha: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alpha'
        },
        n: {
            type: 'integer',
            title: 'N'
        }
    },
    type: 'object',
    required: ['dimension', 'alpha', 'n'],
    title: 'AdminAgreementMetric'
} as const;

export const AdminExportSchema = {
    properties: {
        dataset_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dataset Id'
        },
        items: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    title: 'AdminExport'
} as const;

export const AdminInterUserAgreementMetricSchema = {
    properties: {
        dimension: {
            type: 'string',
            title: 'Dimension'
        },
        left_user_id: {
            type: 'string',
            title: 'Left User Id'
        },
        right_user_id: {
            type: 'string',
            title: 'Right User Id'
        },
        kappa: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kappa'
        },
        overlap: {
            type: 'integer',
            title: 'Overlap'
        }
    },
    type: 'object',
    required: ['dimension', 'left_user_id', 'right_user_id', 'kappa', 'overlap'],
    title: 'AdminInterUserAgreementMetric'
} as const;

export const AdminItemSummarySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus'
        },
        prompt_text: {
            type: 'string',
            title: 'Prompt Text'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RetrievalCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        document_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Id'
        },
        revision: {
            type: 'integer',
            title: 'Revision'
        },
        validation_flags: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Validation Flags'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'eval_type', 'status', 'prompt_text', 'revision'],
    title: 'AdminItemSummary'
} as const;

export const AdminModerationActionSchema = {
    properties: {
        action: {
            type: 'string',
            enum: ['approve', 'reject', 'return_to_draft'],
            title: 'Action'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        expected_item_revision: {
            type: 'integer',
            title: 'Expected Item Revision'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['action', 'dataset_id', 'expected_item_revision'],
    title: 'AdminModerationAction'
} as const;

export const AdminTaskGenerationResultSchema = {
    properties: {
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        created: {
            type: 'integer',
            title: 'Created'
        },
        existing: {
            type: 'integer',
            title: 'Existing'
        }
    },
    type: 'object',
    required: ['dataset_id', 'created', 'existing'],
    title: 'AdminTaskGenerationResult'
} as const;

export const AdminUserMetricSchema = {
    properties: {
        user_id: {
            type: 'string',
            title: 'User Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        reviewer_kind: {
            type: 'string',
            title: 'Reviewer Kind'
        },
        authored_items: {
            type: 'integer',
            title: 'Authored Items'
        },
        fact_decomp_reviews: {
            type: 'integer',
            title: 'Fact Decomp Reviews'
        },
        retrieval_qa_reviews: {
            type: 'integer',
            title: 'Retrieval Qa Reviews'
        },
        relevance_judgments: {
            type: 'integer',
            title: 'Relevance Judgments'
        },
        mean_kappa: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mean Kappa'
        },
        kappa_overlap: {
            type: 'integer',
            title: 'Kappa Overlap',
            default: 0
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'role', 'reviewer_kind', 'authored_items', 'fact_decomp_reviews', 'retrieval_qa_reviews', 'relevance_judgments'],
    title: 'AdminUserMetric'
} as const;

export const AssignmentKindSchema = {
    type: 'string',
    enum: ['REGULAR', 'DOUBLE', 'CALIBRATION', 'TRAP'],
    title: 'AssignmentKind'
} as const;

export const AssignmentModeSchema = {
    type: 'string',
    enum: ['ITEM_AUDIT', 'RELEVANCE'],
    title: 'AssignmentMode'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChunkSummarySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        document_id: {
            type: 'integer',
            title: 'Document Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        position: {
            type: 'integer',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'document_id', 'external_id', 'text', 'position'],
    title: 'ChunkSummary'
} as const;

export const CreateFactDecompDraftSubmitSchema = {
    properties: {
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        document_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Id'
        },
        source_text: {
            type: 'string',
            minLength: 1,
            title: 'Source Text'
        },
        facts: {
            items: {
                '$ref': '#/components/schemas/FactDraft'
            },
            type: 'array',
            title: 'Facts'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus',
            default: 'DRAFT'
        }
    },
    type: 'object',
    required: ['dataset_id', 'source_text', 'facts'],
    title: 'CreateFactDecompDraftSubmit'
} as const;

export const CreateRetrievalDraftSubmitSchema = {
    properties: {
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        document_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Document Ids'
        },
        category: {
            '$ref': '#/components/schemas/RetrievalCategory'
        },
        question: {
            type: 'string',
            minLength: 1,
            title: 'Question'
        },
        expected_answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Answer'
        },
        unanswerable: {
            type: 'boolean',
            title: 'Unanswerable',
            default: false
        },
        gold_evidence_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Gold Evidence Spans'
        },
        trap_evidence_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Trap Evidence Spans'
        },
        why_not_answerable: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Why Not Answerable'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus',
            default: 'DRAFT'
        }
    },
    type: 'object',
    required: ['dataset_id', 'category', 'question'],
    title: 'CreateRetrievalDraftSubmit'
} as const;

export const DatasetCreateSchema = {
    properties: {
        name: {
            type: 'string',
            minLength: 1,
            title: 'Name'
        },
        display_name: {
            type: 'string',
            minLength: 1,
            title: 'Display Name'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'display_name', 'eval_type'],
    title: 'DatasetCreate'
} as const;

export const DatasetSummarySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'name', 'display_name', 'eval_type', 'is_active'],
    title: 'DatasetSummary'
} as const;

export const DocumentCreateSchema = {
    properties: {
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        title: {
            type: 'string',
            minLength: 1,
            title: 'Title'
        },
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        },
        external_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Id'
        }
    },
    type: 'object',
    required: ['dataset_id', 'title', 'content'],
    title: 'DocumentCreate'
} as const;

export const DocumentDetailSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        paragraphs: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Paragraphs'
        },
        chunks: {
            items: {
                '$ref': '#/components/schemas/ChunkSummary'
            },
            type: 'array',
            title: 'Chunks'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'external_id', 'title', 'is_active', 'content'],
    title: 'DocumentDetail'
} as const;

export const DocumentSummarySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        external_id: {
            type: 'string',
            title: 'External Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'external_id', 'title', 'is_active'],
    title: 'DocumentSummary'
} as const;

export const EvalTypeSchema = {
    type: 'string',
    enum: ['RETRIEVAL', 'FACT_DECOMP'],
    title: 'EvalType'
} as const;

export const EvidenceSpanSchema = {
    properties: {
        chunk_id: {
            type: 'integer',
            title: 'Chunk Id'
        },
        start: {
            type: 'integer',
            minimum: 0,
            title: 'Start'
        },
        end: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'End'
        },
        text: {
            type: 'string',
            minLength: 1,
            title: 'Text'
        }
    },
    type: 'object',
    required: ['chunk_id', 'start', 'end', 'text'],
    title: 'EvidenceSpan'
} as const;

export const FactDecompCreateResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus'
        },
        prompt_text: {
            type: 'string',
            title: 'Prompt Text'
        },
        document_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Id'
        },
        facts: {
            items: {
                '$ref': '#/components/schemas/FactDraft'
            },
            type: 'array',
            title: 'Facts'
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        },
        validation: {
            '$ref': '#/components/schemas/ValidationPreview'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'eval_type', 'status', 'prompt_text', 'item_revision', 'validation'],
    title: 'FactDecompCreateResponse'
} as const;

export const FactDecompReviewPayloadSchema = {
    properties: {
        kind: {
            type: 'string',
            const: 'fact_decomp',
            title: 'Kind',
            default: 'fact_decomp'
        },
        dataset: {
            '$ref': '#/components/schemas/ReviewDataset'
        },
        item: {
            '$ref': '#/components/schemas/ReviewItem'
        },
        task_id: {
            type: 'integer',
            title: 'Task Id'
        },
        facts: {
            items: {
                '$ref': '#/components/schemas/ReviewFact'
            },
            type: 'array',
            title: 'Facts'
        },
        rubric_dimensions: {
            items: {
                '$ref': '#/components/schemas/ReviewRubricDimension'
            },
            type: 'array',
            title: 'Rubric Dimensions'
        },
        documents: {
            items: {
                '$ref': '#/components/schemas/DocumentDetail'
            },
            type: 'array',
            title: 'Documents'
        },
        chunks: {
            items: {
                '$ref': '#/components/schemas/ChunkSummary'
            },
            type: 'array',
            title: 'Chunks'
        },
        allowed_actions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Allowed Actions'
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        },
        existing_review: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Existing Review'
        }
    },
    type: 'object',
    required: ['dataset', 'item', 'task_id', 'item_revision'],
    title: 'FactDecompReviewPayload'
} as const;

export const FactDecompReviewSubmissionResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        task_id: {
            type: 'integer',
            title: 'Task Id'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        labels_count: {
            type: 'integer',
            title: 'Labels Count'
        },
        completed: {
            type: 'boolean',
            title: 'Completed',
            default: true
        }
    },
    type: 'object',
    required: ['id', 'task_id', 'item_id', 'labels_count'],
    title: 'FactDecompReviewSubmissionResponse'
} as const;

export const FactDecompReviewSubmitSchema = {
    properties: {
        fact_calls: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Fact Calls'
        },
        values: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Values'
        },
        comments: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comments'
        },
        confidence: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/JudgmentConfidence'
                },
                {
                    type: 'null'
                }
            ]
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        }
    },
    type: 'object',
    required: ['fact_calls', 'values', 'item_revision'],
    title: 'FactDecompReviewSubmit'
} as const;

export const FactDraftSchema = {
    properties: {
        fact_uuid: {
            type: 'string',
            title: 'Fact Uuid'
        },
        fact_text: {
            type: 'string',
            minLength: 1,
            title: 'Fact Text'
        },
        polarity: {
            '$ref': '#/components/schemas/FactPolarity'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        provenance_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Provenance Spans'
        }
    },
    type: 'object',
    required: ['fact_uuid', 'fact_text', 'polarity', 'position'],
    title: 'FactDraft'
} as const;

export const FactPolaritySchema = {
    type: 'string',
    enum: ['SHOULD_LIST', 'SHOULD_NOT_LIST'],
    title: 'FactPolarity'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HomeSummarySchema = {
    properties: {
        user: {
            '$ref': '#/components/schemas/UserPublic'
        },
        outstanding_counts: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Outstanding Counts'
        },
        authored_total: {
            type: 'integer',
            title: 'Authored Total',
            default: 0
        },
        reviewed_total: {
            type: 'integer',
            title: 'Reviewed Total',
            default: 0
        },
        recommended_task: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RecommendedTask'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['user'],
    title: 'HomeSummary'
} as const;

export const ItemStatusSchema = {
    type: 'string',
    enum: ['DRAFT', 'SUBMITTED', 'ACTIVE', 'REJECTED'],
    title: 'ItemStatus'
} as const;

export const JudgmentConfidenceSchema = {
    type: 'string',
    enum: ['EASY_CALL', 'DELIBERATED'],
    title: 'JudgmentConfidence'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NextReviewRecommendationSchema = {
    properties: {
        kind: {
            type: 'string',
            enum: ['retrieval_audit', 'fact_decomp', 'relevance'],
            title: 'Kind'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        review_url: {
            type: 'string',
            title: 'Review Url'
        },
        reservation_state: {
            type: 'string',
            enum: ['existing', 'created', 'selected'],
            title: 'Reservation State'
        },
        assignment_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignment Id'
        },
        task_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Id'
        },
        item_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Item Id'
        }
    },
    type: 'object',
    required: ['kind', 'eval_type', 'dataset_id', 'title', 'reason', 'review_url', 'reservation_state'],
    title: 'NextReviewRecommendation'
} as const;

export const NiceDocumentResponseSchema = {
    properties: {
        document_id: {
            type: 'integer',
            title: 'Document Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        reference: {
            type: 'string',
            title: 'Reference'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        section_count: {
            type: 'integer',
            title: 'Section Count'
        },
        char_count: {
            type: 'integer',
            title: 'Char Count'
        },
        page_url: {
            type: 'string',
            title: 'Page Url'
        }
    },
    type: 'object',
    required: ['document_id', 'dataset_id', 'reference', 'title', 'section_count', 'char_count', 'page_url'],
    title: 'NiceDocumentResponse'
} as const;

export const NiceDownloadSummarySchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        reference: {
            type: 'string',
            title: 'Reference'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        page_url: {
            type: 'string',
            title: 'Page Url'
        },
        page_count: {
            type: 'integer',
            title: 'Page Count'
        },
        char_count: {
            type: 'integer',
            title: 'Char Count'
        }
    },
    type: 'object',
    required: ['id', 'reference', 'title', 'page_url', 'page_count', 'char_count'],
    title: 'NiceDownloadSummary'
} as const;

export const NiceImportJobStatusSchema = {
    type: 'string',
    enum: ['pending', 'running', 'completed', 'failed', 'cancelled'],
    title: 'NiceImportJobStatus'
} as const;

export const NiceImportJobStatusResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        status: {
            '$ref': '#/components/schemas/NiceImportJobStatus'
        },
        requested_limit: {
            '$ref': '#/components/schemas/NiceImportLimit'
        },
        target_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Count'
        },
        completed_count: {
            type: 'integer',
            title: 'Completed Count'
        },
        failed_count: {
            type: 'integer',
            title: 'Failed Count'
        },
        started_by_user_id: {
            type: 'string',
            title: 'Started By User Id'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        last_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Error'
        },
        heartbeat_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Heartbeat At'
        }
    },
    type: 'object',
    required: ['id', 'status', 'requested_limit', 'completed_count', 'failed_count', 'started_by_user_id'],
    title: 'NiceImportJobStatusResponse'
} as const;

export const NiceImportLimitSchema = {
    type: 'string',
    enum: ['10', '20', '50', 'all'],
    title: 'NiceImportLimit'
} as const;

export const NiceImportStartSchema = {
    properties: {
        limit: {
            enum: [10, 20, 50, 'all'],
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['limit'],
    title: 'NiceImportStart'
} as const;

export const NiceUrlRecommendationRequestSchema = {
    properties: {
        dataset_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dataset Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'NiceUrlRecommendationRequest'
} as const;

export const PooledCandidateSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        chunk_id: {
            type: 'integer',
            title: 'Chunk Id'
        },
        systems: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Systems'
        },
        ranks: {
            additionalProperties: true,
            type: 'object',
            title: 'Ranks'
        },
        is_calibration: {
            type: 'boolean',
            title: 'Is Calibration',
            default: false
        },
        is_trap: {
            type: 'boolean',
            title: 'Is Trap',
            default: false
        },
        reference_grade: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Grade'
        }
    },
    type: 'object',
    required: ['dataset_id', 'item_id', 'chunk_id'],
    title: 'PooledCandidate'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RecommendedTaskSchema = {
    properties: {
        kind: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AssignmentKind'
                },
                {
                    type: 'string'
                }
            ],
            title: 'Kind'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        reason: {
            type: 'string',
            title: 'Reason'
        },
        assignment_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignment Id'
        },
        task_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Id'
        }
    },
    type: 'object',
    required: ['kind', 'eval_type', 'dataset_id', 'title', 'reason'],
    title: 'RecommendedTask'
} as const;

export const RelevanceReviewPayloadSchema = {
    properties: {
        kind: {
            type: 'string',
            const: 'relevance',
            title: 'Kind',
            default: 'relevance'
        },
        dataset: {
            '$ref': '#/components/schemas/ReviewDataset'
        },
        item: {
            '$ref': '#/components/schemas/ReviewItem'
        },
        assignment_id: {
            type: 'integer',
            title: 'Assignment Id'
        },
        candidate: {
            '$ref': '#/components/schemas/PooledCandidate'
        },
        document: {
            '$ref': '#/components/schemas/DocumentDetail'
        },
        chunk: {
            '$ref': '#/components/schemas/ChunkSummary'
        },
        allowed_actions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Allowed Actions'
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        },
        existing_submission: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Existing Submission'
        }
    },
    type: 'object',
    required: ['dataset', 'item', 'assignment_id', 'candidate', 'document', 'chunk', 'item_revision'],
    title: 'RelevanceReviewPayload'
} as const;

export const RelevanceReviewSubmitSchema = {
    properties: {
        grade: {
            type: 'integer',
            maximum: 3,
            minimum: 0,
            title: 'Grade'
        },
        confidence: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/JudgmentConfidence'
                },
                {
                    type: 'null'
                }
            ]
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        }
    },
    type: 'object',
    required: ['grade', 'item_revision'],
    title: 'RelevanceReviewSubmit'
} as const;

export const RetrievalCategorySchema = {
    type: 'string',
    enum: ['VERBATIM', 'PARAPHRASE', 'MULTI_CHUNK', 'ADVERSARIAL', 'MULTI_DOCUMENT'],
    title: 'RetrievalCategory'
} as const;

export const RetrievalCreateResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        category: {
            '$ref': '#/components/schemas/RetrievalCategory'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus'
        },
        prompt_text: {
            type: 'string',
            title: 'Prompt Text'
        },
        expected_answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Answer'
        },
        evidence_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Evidence Spans'
        },
        trap_evidence_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Trap Evidence Spans'
        },
        document_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Document Ids'
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        },
        validation: {
            '$ref': '#/components/schemas/ValidationPreview'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'eval_type', 'category', 'status', 'prompt_text', 'item_revision', 'validation'],
    title: 'RetrievalCreateResponse'
} as const;

export const RetrievalReviewPayloadSchema = {
    properties: {
        kind: {
            type: 'string',
            const: 'retrieval_audit',
            title: 'Kind',
            default: 'retrieval_audit'
        },
        dataset: {
            '$ref': '#/components/schemas/ReviewDataset'
        },
        item: {
            '$ref': '#/components/schemas/ReviewItem'
        },
        assignment_id: {
            type: 'integer',
            title: 'Assignment Id'
        },
        documents: {
            items: {
                '$ref': '#/components/schemas/DocumentDetail'
            },
            type: 'array',
            title: 'Documents'
        },
        chunks: {
            items: {
                '$ref': '#/components/schemas/ChunkSummary'
            },
            type: 'array',
            title: 'Chunks'
        },
        gold_evidence_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Gold Evidence Spans'
        },
        trap_evidence_spans: {
            items: {
                '$ref': '#/components/schemas/EvidenceSpan'
            },
            type: 'array',
            title: 'Trap Evidence Spans'
        },
        allowed_actions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Allowed Actions'
        },
        item_revision: {
            type: 'integer',
            title: 'Item Revision'
        },
        existing_submission: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Existing Submission'
        }
    },
    type: 'object',
    required: ['dataset', 'item', 'assignment_id', 'item_revision'],
    title: 'RetrievalReviewPayload'
} as const;

export const RetrievalReviewSubmitSchema = {
    properties: {
        question_validity: {
            type: 'integer',
            enum: [1, 2, 3, 4],
            title: 'Question Validity'
        },
        evidence_quality: {
            type: 'integer',
            enum: [1, 2, 3, 4],
            title: 'Evidence Quality'
        },
        answer_correctness: {
            type: 'integer',
            enum: [1, 2, 3, 4],
            title: 'Answer Correctness'
        },
        answer_faithfulness: {
            type: 'integer',
            enum: [1, 2, 3, 4],
            title: 'Answer Faithfulness'
        },
        accept_as_gold: {
            type: 'boolean',
            title: 'Accept As Gold'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['question_validity', 'evidence_quality', 'answer_correctness', 'answer_faithfulness', 'accept_as_gold'],
    title: 'RetrievalReviewSubmit'
} as const;

export const ReviewDatasetSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        }
    },
    type: 'object',
    required: ['id', 'name', 'display_name', 'eval_type'],
    title: 'ReviewDataset'
} as const;

export const ReviewFactSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        fact_uuid: {
            type: 'string',
            title: 'Fact Uuid'
        },
        fact_text: {
            type: 'string',
            title: 'Fact Text'
        },
        polarity: {
            '$ref': '#/components/schemas/FactPolarity'
        },
        position: {
            type: 'integer',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'fact_uuid', 'fact_text', 'polarity', 'position'],
    title: 'ReviewFact'
} as const;

export const ReviewItemSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_id: {
            type: 'integer',
            title: 'Dataset Id'
        },
        eval_type: {
            '$ref': '#/components/schemas/EvalType'
        },
        prompt_text: {
            type: 'string',
            title: 'Prompt Text'
        },
        status: {
            '$ref': '#/components/schemas/ItemStatus'
        },
        revision: {
            type: 'integer',
            title: 'Revision'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RetrievalCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        expected_answer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Answer'
        },
        why_not_answerable: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Why Not Answerable'
        }
    },
    type: 'object',
    required: ['id', 'dataset_id', 'eval_type', 'prompt_text', 'status', 'revision'],
    title: 'ReviewItem'
} as const;

export const ReviewRubricDimensionSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Options'
        }
    },
    type: 'object',
    required: ['key', 'label'],
    title: 'ReviewRubricDimension'
} as const;

export const ReviewSubmissionResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        assignment_id: {
            type: 'integer',
            title: 'Assignment Id'
        },
        item_id: {
            type: 'integer',
            title: 'Item Id'
        },
        kind: {
            type: 'string',
            enum: ['retrieval_audit', 'relevance'],
            title: 'Kind'
        },
        completed: {
            type: 'boolean',
            title: 'Completed',
            default: true
        }
    },
    type: 'object',
    required: ['id', 'assignment_id', 'item_id', 'kind'],
    title: 'ReviewSubmissionResponse'
} as const;

export const ReviewerKindSchema = {
    type: 'string',
    enum: ['human', 'expert'],
    title: 'ReviewerKind'
} as const;

export const SignupInviteCreateSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/UserRole',
            maxLength: 32,
            default: 'user'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        max_redemptions: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Max Redemptions',
            default: 1
        }
    },
    type: 'object',
    title: 'SignupInviteCreate'
} as const;

export const SignupInviteCreatedSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/UserRole',
            maxLength: 32,
            default: 'user'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        max_redemptions: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Max Redemptions',
            default: 1
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        redeemed_count: {
            type: 'integer',
            title: 'Redeemed Count'
        },
        disabled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disabled At'
        },
        created_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By User Id'
        },
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['id', 'redeemed_count', 'token'],
    title: 'SignupInviteCreated'
} as const;

export const SignupInvitePreviewSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/UserRole'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        remaining_redemptions: {
            type: 'integer',
            title: 'Remaining Redemptions'
        }
    },
    type: 'object',
    required: ['role', 'remaining_redemptions'],
    title: 'SignupInvitePreview'
} as const;

export const SignupInvitePublicSchema = {
    properties: {
        role: {
            '$ref': '#/components/schemas/UserRole',
            maxLength: 32,
            default: 'user'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        },
        max_redemptions: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Max Redemptions',
            default: 1
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        redeemed_count: {
            type: 'integer',
            title: 'Redeemed Count'
        },
        disabled_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disabled At'
        },
        created_by_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By User Id'
        }
    },
    type: 'object',
    required: ['id', 'redeemed_count'],
    title: 'SignupInvitePublic'
} as const;

export const SignupInvitesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SignupInvitePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SignupInvitesPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        discord_handle: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discord Handle'
        },
        medical_profession: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Medical Profession'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            maxLength: 32,
            default: 'user'
        },
        reviewer_kind: {
            '$ref': '#/components/schemas/ReviewerKind',
            maxLength: 32,
            default: 'human'
        },
        expertise_note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expertise Note'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        discord_handle: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discord Handle'
        },
        medical_profession: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Medical Profession'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            maxLength: 32,
            default: 'user'
        },
        reviewer_kind: {
            '$ref': '#/components/schemas/ReviewerKind',
            maxLength: 32,
            default: 'human'
        },
        expertise_note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expertise Note'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        invite_token: {
            type: 'string',
            maxLength: 255,
            minLength: 16,
            title: 'Invite Token'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        discord_handle: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discord Handle'
        },
        medical_profession: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Medical Profession'
        }
    },
    type: 'object',
    required: ['invite_token', 'email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['user', 'data_admin', 'admin'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        discord_handle: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discord Handle'
        },
        medical_profession: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Medical Profession'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            maxLength: 32,
            default: 'user'
        },
        reviewer_kind: {
            '$ref': '#/components/schemas/ReviewerKind',
            maxLength: 32,
            default: 'human'
        },
        expertise_note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expertise Note'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        discord_handle: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discord Handle'
        },
        medical_profession: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Medical Profession'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const ValidationPreviewSchema = {
    properties: {
        ok: {
            type: 'boolean',
            title: 'Ok'
        },
        flags: {
            items: {
                additionalProperties: {
                    type: 'string'
                },
                type: 'object'
            },
            type: 'array',
            title: 'Flags'
        }
    },
    type: 'object',
    required: ['ok'],
    title: 'ValidationPreview'
} as const;