// This file is auto-generated by @hey-api/openapi-ts

export type AdminAgreementMetric = {
    alpha: (number | null);
    dimension: string;
    n: number;
};

export type AdminExport = {
    dataset_id?: (number | null);
    items?: Array<{
        [key: string]: unknown;
    }>;
};

export type AdminInterUserAgreementMetric = {
    dimension: string;
    kappa: (number | null);
    left_user_id: string;
    overlap: number;
    right_user_id: string;
};

export type AdminItemSummary = {
    category?: (RetrievalCategory | null);
    dataset_id: number;
    document_id?: (number | null);
    eval_type: EvalType;
    id: number;
    prompt_text: string;
    revision: number;
    status: ItemStatus;
    validation_flags?: Array<{
        [key: string]: unknown;
    }>;
};

export type AdminModerationAction = {
    action: 'approve' | 'reject' | 'return_to_draft';
    dataset_id: number;
    expected_item_revision: number;
    reason?: (string | null);
};

export type action = 'approve' | 'reject' | 'return_to_draft';

export type AdminTaskGenerationResult = {
    created: number;
    dataset_id: number;
    existing: number;
};

export type AdminUserMetric = {
    authored_items: number;
    email: string;
    fact_decomp_reviews: number;
    kappa_overlap?: number;
    mean_kappa?: (number | null);
    relevance_judgments: number;
    retrieval_qa_reviews: number;
    reviewer_kind: string;
    role: string;
    user_id: string;
};

export type AssignmentKind = 'REGULAR' | 'DOUBLE' | 'CALIBRATION' | 'TRAP';

export type AssignmentMode = 'ITEM_AUDIT' | 'RELEVANCE';

/**
 * Record why an incomplete assignment is being returned to the queue.
 */
export type AssignmentRelease = {
    reason: string;
};

export type AssignmentReleaseResponse = {
    id: number;
    release_reason: string;
    released?: boolean;
};

export type Body_auth_preview_invite = {
    token: string;
};

export type Body_login_login_access_token = {
    client_id?: (string | null);
    client_secret?: (string | null);
    grant_type?: (string | null);
    password: string;
    scope?: string;
    username: string;
};

export type ChunkSummary = {
    dataset_id: number;
    document_id: number;
    external_id: string;
    id: number;
    position: number;
    text: string;
};

export type CreateFactDecompDraftSubmit = {
    dataset_id: number;
    document_id?: (number | null);
    facts: Array<FactDraft>;
    source_text: string;
    status?: ItemStatus;
};

export type CreateRetrievalDraftSubmit = {
    category: RetrievalCategory;
    dataset_id: number;
    document_ids?: Array<(number)>;
    expected_answer?: (string | null);
    gold_evidence_spans?: Array<EvidenceSpan>;
    question: string;
    status?: ItemStatus;
    trap_evidence_spans?: Array<EvidenceSpan>;
    unanswerable?: boolean;
    why_not_answerable?: (string | null);
};

export type DatasetCreate = {
    description?: (string | null);
    display_name: string;
    eval_type: EvalType;
    is_active?: boolean;
    name: string;
};

export type DatasetSummary = {
    display_name: string;
    eval_type: EvalType;
    id: number;
    is_active: boolean;
    name: string;
};

export type DocumentCreate = {
    content: string;
    dataset_id: number;
    external_id?: (string | null);
    title: string;
};

export type DocumentDetail = {
    chunks?: Array<ChunkSummary>;
    content: string;
    dataset_id: number;
    external_id: string;
    id: number;
    is_active: boolean;
    paragraphs?: Array<{
        [key: string]: unknown;
    }>;
    title: string;
};

export type DocumentSummary = {
    dataset_id: number;
    external_id: string;
    id: number;
    is_active: boolean;
    title: string;
};

export type EvalType = 'RETRIEVAL' | 'FACT_DECOMP';

export type EvidenceSpan = {
    chunk_id: number;
    end: number;
    start: number;
    text: string;
};

export type FactDecompCreateResponse = {
    dataset_id: number;
    document_id?: (number | null);
    eval_type: EvalType;
    facts?: Array<FactDraft>;
    id: number;
    item_revision: number;
    prompt_text: string;
    status: ItemStatus;
    validation: ValidationPreview;
};

export type FactDecompReviewPayload = {
    allowed_actions?: Array<(string)>;
    chunks?: Array<ChunkSummary>;
    dataset: ReviewDataset;
    documents?: Array<DocumentDetail>;
    existing_review?: ({
    [key: string]: unknown;
} | null);
    facts?: Array<ReviewFact>;
    item: ReviewItem;
    item_revision: number;
    kind?: "fact_decomp";
    rubric_dimensions?: Array<ReviewRubricDimension>;
    task_id: number;
};

export type FactDecompReviewSubmissionResponse = {
    completed?: boolean;
    id: number;
    item_id: number;
    labels_count: number;
    task_id: number;
};

export type FactDecompReviewSubmit = {
    comments?: (string | null);
    confidence?: (JudgmentConfidence | null);
    fact_calls: {
        [key: string]: (string);
    };
    item_revision: number;
    values: {
        [key: string]: (string);
    };
};

export type FactDraft = {
    fact_text: string;
    fact_uuid: string;
    polarity: FactPolarity;
    position: number;
    provenance_spans?: Array<EvidenceSpan>;
};

export type FactPolarity = 'SHOULD_LIST' | 'SHOULD_NOT_LIST';

export type HomeSummary = {
    authored_total?: number;
    outstanding_counts?: {
        [key: string]: (number);
    };
    recommended_task?: (RecommendedTask | null);
    reviewed_total?: number;
    user: UserPublic;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Signup payload that lets the route normalize malformed invite tokens.
 */
export type InviteSignupRequest = {
    discord_handle?: (string | null);
    email: string;
    full_name?: (string | null);
    invite_token: string;
    medical_profession?: (string | null);
    password: string;
};

export type ItemStatus = 'DRAFT' | 'SUBMITTED' | 'ACTIVE' | 'REJECTED';

export type ItemVerdict = 'ACCEPT' | 'REJECT';

export type JudgmentConfidence = 'EASY_CALL' | 'DELIBERATED';

export type Message = {
    message: string;
};

export type NewPassword = {
    new_password: string;
    token: string;
};

export type NextReviewRecommendation = {
    assignment_id?: (number | null);
    dataset_id: number;
    eval_type: EvalType;
    item_id?: (number | null);
    kind: 'retrieval_audit' | 'fact_decomp' | 'relevance';
    reason: string;
    reservation_state: 'existing' | 'created' | 'selected';
    review_url: string;
    task_id?: (number | null);
    title: string;
};

export type kind = 'retrieval_audit' | 'fact_decomp' | 'relevance';

export type reservation_state = 'existing' | 'created' | 'selected';

export type NiceDocumentResponse = {
    char_count: number;
    dataset_id: number;
    document_id: number;
    page_url: string;
    reference: string;
    section_count: number;
    title: string;
};

export type NiceDownloadSummary = {
    char_count: number;
    id: number;
    page_count: number;
    page_url: string;
    reference: string;
    title: string;
};

export type NiceImportJobStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

export type NiceImportJobStatusResponse = {
    completed_count: number;
    failed_count: number;
    finished_at?: (string | null);
    heartbeat_at?: (string | null);
    id: number;
    last_error?: (string | null);
    requested_limit: NiceImportLimit;
    started_at?: (string | null);
    started_by_user_id: string;
    status: NiceImportJobStatus;
    target_count?: (number | null);
};

export type NiceImportLimit = '10' | '20' | '50' | 'all';

export type NiceImportStart = {
    limit: 10 | 20 | 50 | 'all';
};

export type limit = 10 | 20 | 50 | 'all';

export type NiceUrlRecommendationRequest = {
    dataset_id?: (number | null);
    url: string;
};

export type PooledCandidate = {
    chunk_id: number;
    created_at?: string;
    dataset_id: number;
    id?: (number | null);
    is_calibration?: boolean;
    is_trap?: boolean;
    item_id: number;
    ranks?: {
        [key: string]: unknown;
    };
    reference_grade?: (number | null);
    systems?: Array<(string)>;
    updated_at?: string;
};

export type RecommendedTask = {
    assignment_id?: (number | null);
    dataset_id: number;
    eval_type: EvalType;
    kind: (AssignmentKind | string);
    reason: string;
    task_id?: (number | null);
    title: string;
};

export type RelevanceReviewPayload = {
    allowed_actions?: Array<(string)>;
    assignment_id: number;
    candidate: PooledCandidate;
    chunk: ChunkSummary;
    dataset: ReviewDataset;
    document: DocumentDetail;
    existing_submission?: ({
    [key: string]: unknown;
} | null);
    item: ReviewItem;
    item_revision: number;
    kind?: "relevance";
};

export type RelevanceReviewSubmit = {
    confidence?: (JudgmentConfidence | null);
    grade: number;
    item_revision: number;
};

export type RetrievalCategory = 'VERBATIM' | 'PARAPHRASE' | 'MULTI_CHUNK' | 'ADVERSARIAL' | 'MULTI_DOCUMENT';

export type RetrievalCreateResponse = {
    category: RetrievalCategory;
    dataset_id: number;
    document_ids?: Array<(number)>;
    eval_type: EvalType;
    evidence_spans?: Array<EvidenceSpan>;
    expected_answer?: (string | null);
    id: number;
    item_revision: number;
    prompt_text: string;
    status: ItemStatus;
    trap_evidence_spans?: Array<EvidenceSpan>;
    validation: ValidationPreview;
};

export type RetrievalReviewPayload = {
    allowed_actions?: Array<(string)>;
    assignment_id: number;
    chunks?: Array<ChunkSummary>;
    dataset: ReviewDataset;
    documents?: Array<DocumentDetail>;
    existing_submission?: (RetrievalReviewSubmission | null);
    gold_evidence_spans?: Array<EvidenceSpan>;
    item: ReviewItem;
    item_revision: number;
    kind?: "retrieval_audit";
    trap_evidence_spans?: Array<EvidenceSpan>;
};

/**
 * Canonical persisted retrieval-review state returned to a reviewer.
 */
export type RetrievalReviewSubmission = {
    answer_correctness?: (number | null);
    answer_faithfulness?: (number | null);
    evidence_quality?: (number | null);
    id: number;
    notes?: (string | null);
    question_validity?: (number | null);
    skip_reason?: (string | null);
    skipped: boolean;
    verdict?: (ItemVerdict | null);
};

export type RetrievalReviewSubmit = {
    accept_as_gold?: (boolean | null);
    answer_correctness?: (1 | 2 | 3 | 4 | null);
    answer_faithfulness?: (1 | 2 | 3 | 4 | null);
    evidence_quality?: (1 | 2 | 3 | 4 | null);
    notes?: (string | null);
    question_validity?: (1 | 2 | 3 | 4 | null);
    skip_reason?: (string | null);
    skipped?: boolean;
};

/**
 * Request one review claim in a selected evaluation dataset.
 */
export type ReviewClaimRequest = {
    dataset_id?: (number | null);
    eval_type: EvalType;
    mode?: AssignmentMode;
};

export type ReviewDataset = {
    display_name: string;
    eval_type: EvalType;
    id: number;
    name: string;
};

export type ReviewerKind = 'human' | 'expert';

export type ReviewFact = {
    fact_text: string;
    fact_uuid: string;
    id: number;
    polarity: FactPolarity;
    position: number;
};

export type ReviewItem = {
    category?: (RetrievalCategory | null);
    dataset_id: number;
    eval_type: EvalType;
    expected_answer?: (string | null);
    id: number;
    prompt_text: string;
    revision: number;
    status: ItemStatus;
    why_not_answerable?: (string | null);
};

export type ReviewRubricDimension = {
    key: string;
    label: string;
    options?: Array<(string)>;
};

export type ReviewSubmissionResponse = {
    assignment_id: number;
    completed?: boolean;
    id: number;
    item_id: number;
    kind: 'retrieval_audit' | 'relevance';
};

export type kind2 = 'retrieval_audit' | 'relevance';

export type SignupInviteCreate = {
    expires_at?: (string | null);
    max_redemptions?: number;
    role?: UserRole;
};

export type SignupInviteCreated = {
    created_at?: (string | null);
    created_by_user_id?: (string | null);
    disabled_at?: (string | null);
    expires_at?: (string | null);
    id: string;
    max_redemptions?: number;
    redeemed_count: number;
    role?: UserRole;
    token: string;
};

export type SignupInvitePreview = {
    expires_at?: (string | null);
    remaining_redemptions: number;
    role: UserRole;
};

export type SignupInvitePublic = {
    created_at?: (string | null);
    created_by_user_id?: (string | null);
    disabled_at?: (string | null);
    expires_at?: (string | null);
    id: string;
    max_redemptions?: number;
    redeemed_count: number;
    role?: UserRole;
};

export type SignupInvitesPublic = {
    count: number;
    data: Array<SignupInvitePublic>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    discord_handle?: (string | null);
    email: string;
    expertise_note?: (string | null);
    full_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    medical_profession?: (string | null);
    password: string;
    reviewer_kind?: ReviewerKind;
    role?: UserRole;
};

export type UserPublic = {
    created_at?: (string | null);
    discord_handle?: (string | null);
    email: string;
    expertise_note?: (string | null);
    full_name?: (string | null);
    id: string;
    is_active?: boolean;
    is_superuser?: boolean;
    medical_profession?: (string | null);
    reviewer_kind?: ReviewerKind;
    role?: UserRole;
};

export type UserRole = 'user' | 'data_admin' | 'admin';

export type UsersPublic = {
    count: number;
    data: Array<UserPublic>;
};

export type UserUpdate = {
    discord_handle?: (string | null);
    email?: (string | null);
    expertise_note?: (string | null);
    full_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    medical_profession?: (string | null);
    password?: (string | null);
    reviewer_kind?: ReviewerKind;
    role?: UserRole;
};

export type UserUpdateMe = {
    discord_handle?: (string | null);
    email?: (string | null);
    full_name?: (string | null);
    medical_profession?: (string | null);
};

export type ValidationError = {
    ctx?: {
        [key: string]: unknown;
    };
    input?: unknown;
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ValidationPreview = {
    flags?: Array<{
        [key: string]: (string);
    }>;
    ok: boolean;
};

export type AdminReadAdminDatasetsResponse = (Array<DatasetSummary>);

export type AdminCreateAdminDatasetData = {
    requestBody: DatasetCreate;
};

export type AdminCreateAdminDatasetResponse = (DatasetSummary);

export type AdminReadAdminDatasetData = {
    datasetId: number;
};

export type AdminReadAdminDatasetResponse = (DatasetSummary);

export type AdminGenerateDatasetTasksData = {
    datasetId: number;
};

export type AdminGenerateDatasetTasksResponse = (AdminTaskGenerationResult);

export type AdminReadAdminDocumentsResponse = (Array<DocumentSummary>);

export type AdminCreateAdminDocumentData = {
    requestBody: DocumentCreate;
};

export type AdminCreateAdminDocumentResponse = (DocumentDetail);

export type AdminReadAdminDocumentData = {
    documentId: number;
};

export type AdminReadAdminDocumentResponse = (DocumentDetail);

export type AdminToggleAdminDocumentData = {
    documentId: number;
};

export type AdminToggleAdminDocumentResponse = (DocumentSummary);

export type AdminExportDatasetData = {
    datasetId?: (number | null);
};

export type AdminExportDatasetResponse = (AdminExport);

export type AdminIngestDatasetResponse = (unknown);

export type AdminReadAdminItemsData = {
    datasetId?: (number | null);
    status?: (ItemStatus | null);
};

export type AdminReadAdminItemsResponse = (Array<AdminItemSummary>);

export type AdminApproveAdminItemData = {
    itemId: number;
    requestBody: AdminModerationAction;
};

export type AdminApproveAdminItemResponse = (AdminItemSummary);

export type AdminRejectAdminItemData = {
    itemId: number;
    requestBody: AdminModerationAction;
};

export type AdminRejectAdminItemResponse = (AdminItemSummary);

export type AdminReadAgreementMetricsData = {
    datasetId?: (number | null);
    reviewerKind?: (ReviewerKind | null);
};

export type AdminReadAgreementMetricsResponse = (Array<AdminAgreementMetric>);

export type AdminReadInterUserAgreementData = {
    datasetId?: (number | null);
    minOverlap?: number;
};

export type AdminReadInterUserAgreementResponse = (Array<AdminInterUserAgreementMetric>);

export type AdminReadUserMetricsData = {
    datasetId?: (number | null);
};

export type AdminReadUserMetricsResponse = (Array<AdminUserMetric>);

export type AdminStartNiceImportData = {
    requestBody: NiceImportStart;
};

export type AdminStartNiceImportResponse = (NiceImportJobStatusResponse);

export type AdminReadCurrentNiceImportResponse = ((NiceImportJobStatusResponse | null));

export type AdminCancelNiceImportData = {
    jobId: number;
};

export type AdminCancelNiceImportResponse = (NiceImportJobStatusResponse);

export type AdminReadAdminUsersResponse = (unknown);

export type AdminUpdateAdminUserData = {
    userId: string;
};

export type AdminUpdateAdminUserResponse = (unknown);

export type AdminReadAdminUserReviewsData = {
    userId: string;
};

export type AdminReadAdminUserReviewsResponse = (unknown);

export type AuthListInvitesResponse = (SignupInvitesPublic);

export type AuthCreateInviteData = {
    requestBody: SignupInviteCreate;
};

export type AuthCreateInviteResponse = (SignupInviteCreated);

export type AuthPreviewInviteData = {
    requestBody: Body_auth_preview_invite;
};

export type AuthPreviewInviteResponse = (SignupInvitePreview);

export type AuthDisableInviteData = {
    inviteId: string;
};

export type AuthDisableInviteResponse = (SignupInvitePublic);

export type AuthInviteSignupData = {
    requestBody: InviteSignupRequest;
};

export type AuthInviteSignupResponse = (Token);

export type CreateCreateFactDecompDraftData = {
    requestBody: CreateFactDecompDraftSubmit;
};

export type CreateCreateFactDecompDraftResponse = (FactDecompCreateResponse);

export type CreateSubmitFactDecompDraftData = {
    requestBody: CreateFactDecompDraftSubmit;
};

export type CreateSubmitFactDecompDraftResponse = (FactDecompCreateResponse);

export type CreateReadCreateOptionsResponse = (Array<DatasetSummary>);

export type CreateCreateRetrievalDraftData = {
    requestBody: CreateRetrievalDraftSubmit;
};

export type CreateCreateRetrievalDraftResponse = (RetrievalCreateResponse);

export type CreateSubmitRetrievalDraftData = {
    requestBody: CreateRetrievalDraftSubmit;
};

export type CreateSubmitRetrievalDraftResponse = (RetrievalCreateResponse);

export type CreateReadSourceDocumentsData = {
    datasetId: number;
    evalType: EvalType;
    includeUsed?: boolean;
};

export type CreateReadSourceDocumentsResponse = (Array<DocumentSummary>);

export type CreateReadSourceDocumentDetailData = {
    datasetId: number;
    documentId: number;
    evalType: EvalType;
};

export type CreateReadSourceDocumentDetailResponse = (DocumentDetail);

export type CreateValidateCreationRequestData = {
    requestBody: (CreateRetrievalDraftSubmit | CreateFactDecompDraftSubmit);
};

export type CreateValidateCreationRequestResponse = (ValidationPreview);

export type HomeReadHomeSummaryResponse = (HomeSummary);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type NiceListNiceDownloadsResponse = (Array<NiceDownloadSummary>);

export type NiceFetchNiceRecommendationByUrlData = {
    requestBody: NiceUrlRecommendationRequest;
};

export type NiceFetchNiceRecommendationByUrlResponse = (NiceDocumentResponse);

export type ReviewReleaseReviewAssignmentData = {
    assignmentId: number;
    requestBody: AssignmentRelease;
};

export type ReviewReleaseReviewAssignmentResponse = (AssignmentReleaseResponse);

export type ReviewClaimNextReviewTaskData = {
    requestBody: ReviewClaimRequest;
};

export type ReviewClaimNextReviewTaskResponse = (NextReviewRecommendation);

export type ReviewReadFactDecompReviewData = {
    taskId: number;
};

export type ReviewReadFactDecompReviewResponse = (FactDecompReviewPayload);

export type ReviewSubmitFactDecompReviewData = {
    requestBody: FactDecompReviewSubmit;
    taskId: number;
};

export type ReviewSubmitFactDecompReviewResponse = (FactDecompReviewSubmissionResponse);

export type ReviewReadNextReviewTaskData = {
    evalType: EvalType;
    mode?: AssignmentMode;
};

export type ReviewReadNextReviewTaskResponse = (NextReviewRecommendation);

export type ReviewReadRelevanceReviewData = {
    assignmentId: number;
};

export type ReviewReadRelevanceReviewResponse = (RelevanceReviewPayload);

export type ReviewSubmitRelevanceReviewData = {
    assignmentId: number;
    requestBody: RelevanceReviewSubmit;
};

export type ReviewSubmitRelevanceReviewResponse = (ReviewSubmissionResponse);

export type ReviewReadRetrievalReviewData = {
    assignmentId: number;
};

export type ReviewReadRetrievalReviewResponse = (RetrievalReviewPayload);

export type ReviewSubmitRetrievalReviewData = {
    assignmentId: number;
    requestBody: RetrievalReviewSubmit;
};

export type ReviewSubmitRetrievalReviewResponse = (ReviewSubmissionResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);