// This file is auto-generated by @hey-api/openapi-ts

export type AdminAgreementMetric = {
    dimension: string;
    alpha: (number | null);
    n: number;
};

export type AdminExport = {
    dataset_id?: (number | null);
    items?: Array<{
        [key: string]: unknown;
    }>;
};

export type AdminInterUserAgreementMetric = {
    dimension: string;
    left_user_id: string;
    right_user_id: string;
    kappa: (number | null);
    overlap: number;
};

export type AdminItemSummary = {
    id: number;
    dataset_id: number;
    eval_type: EvalType;
    status: ItemStatus;
    prompt_text: string;
    category?: (RetrievalCategory | null);
    document_id?: (number | null);
    revision: number;
    validation_flags?: Array<{
        [key: string]: unknown;
    }>;
};

export type AdminModerationAction = {
    action: 'approve' | 'reject' | 'return_to_draft';
    dataset_id: number;
    expected_item_revision: number;
    reason?: (string | null);
};

export type action = 'approve' | 'reject' | 'return_to_draft';

export type AdminTaskGenerationResult = {
    dataset_id: number;
    created: number;
    existing: number;
};

export type AdminUserMetric = {
    user_id: string;
    email: string;
    role: string;
    reviewer_kind: string;
    authored_items: number;
    fact_decomp_reviews: number;
    retrieval_qa_reviews: number;
    relevance_judgments: number;
    mean_kappa?: (number | null);
    kappa_overlap?: number;
};

export type AssignmentKind = 'REGULAR' | 'DOUBLE' | 'CALIBRATION' | 'TRAP';

export type AssignmentMode = 'ITEM_AUDIT' | 'RELEVANCE';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChunkSummary = {
    id: number;
    dataset_id: number;
    document_id: number;
    external_id: string;
    text: string;
    position: number;
};

export type CreateFactDecompDraftSubmit = {
    dataset_id: number;
    document_id?: (number | null);
    source_text: string;
    facts: Array<FactDraft>;
    status?: ItemStatus;
};

export type CreateRetrievalDraftSubmit = {
    dataset_id: number;
    document_ids?: Array<(number)>;
    category: RetrievalCategory;
    question: string;
    expected_answer?: (string | null);
    unanswerable?: boolean;
    gold_evidence_spans?: Array<EvidenceSpan>;
    trap_evidence_spans?: Array<EvidenceSpan>;
    why_not_answerable?: (string | null);
    status?: ItemStatus;
};

export type DatasetCreate = {
    name: string;
    display_name: string;
    eval_type: EvalType;
    description?: (string | null);
    is_active?: boolean;
};

export type DatasetSummary = {
    id: number;
    name: string;
    display_name: string;
    eval_type: EvalType;
    is_active: boolean;
};

export type DocumentCreate = {
    dataset_id: number;
    title: string;
    content: string;
    external_id?: (string | null);
};

export type DocumentDetail = {
    id: number;
    dataset_id: number;
    external_id: string;
    title: string;
    is_active: boolean;
    content: string;
    paragraphs?: Array<{
        [key: string]: unknown;
    }>;
    chunks?: Array<ChunkSummary>;
};

export type DocumentSummary = {
    id: number;
    dataset_id: number;
    external_id: string;
    title: string;
    is_active: boolean;
};

export type EvalType = 'RETRIEVAL' | 'FACT_DECOMP';

export type EvidenceSpan = {
    chunk_id: number;
    start: number;
    end: number;
    text: string;
};

export type FactDecompCreateResponse = {
    id: number;
    dataset_id: number;
    eval_type: EvalType;
    status: ItemStatus;
    prompt_text: string;
    document_id?: (number | null);
    facts?: Array<FactDraft>;
    item_revision: number;
    validation: ValidationPreview;
};

export type FactDecompReviewPayload = {
    kind?: "fact_decomp";
    dataset: ReviewDataset;
    item: ReviewItem;
    task_id: number;
    facts?: Array<ReviewFact>;
    rubric_dimensions?: Array<ReviewRubricDimension>;
    documents?: Array<DocumentDetail>;
    chunks?: Array<ChunkSummary>;
    allowed_actions?: Array<(string)>;
    item_revision: number;
    existing_review?: ({
    [key: string]: unknown;
} | null);
};

export type FactDecompReviewSubmissionResponse = {
    id: number;
    task_id: number;
    item_id: number;
    labels_count: number;
    completed?: boolean;
};

export type FactDecompReviewSubmit = {
    fact_calls: {
        [key: string]: (string);
    };
    values: {
        [key: string]: (string);
    };
    comments?: (string | null);
    confidence?: (JudgmentConfidence | null);
    item_revision: number;
};

export type FactDraft = {
    fact_uuid: string;
    fact_text: string;
    polarity: FactPolarity;
    position: number;
    provenance_spans?: Array<EvidenceSpan>;
};

export type FactPolarity = 'SHOULD_LIST' | 'SHOULD_NOT_LIST';

export type HomeSummary = {
    user: UserPublic;
    outstanding_counts?: {
        [key: string]: (number);
    };
    authored_total?: number;
    reviewed_total?: number;
    recommended_task?: (RecommendedTask | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemStatus = 'DRAFT' | 'SUBMITTED' | 'ACTIVE' | 'REJECTED';

export type JudgmentConfidence = 'EASY_CALL' | 'DELIBERATED';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NextReviewRecommendation = {
    kind: 'retrieval_audit' | 'fact_decomp' | 'relevance';
    eval_type: EvalType;
    dataset_id: number;
    title: string;
    reason: string;
    review_url: string;
    reservation_state: 'existing' | 'created' | 'selected';
    assignment_id?: (number | null);
    task_id?: (number | null);
    item_id?: (number | null);
};

export type kind = 'retrieval_audit' | 'fact_decomp' | 'relevance';

export type reservation_state = 'existing' | 'created' | 'selected';

export type NiceDocumentResponse = {
    document_id: number;
    dataset_id: number;
    reference: string;
    title: string;
    section_count: number;
    char_count: number;
    page_url: string;
};

export type NiceDownloadSummary = {
    id: number;
    reference: string;
    title: string;
    page_url: string;
    page_count: number;
    char_count: number;
};

export type NiceImportJobStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

export type NiceImportJobStatusResponse = {
    id: number;
    status: NiceImportJobStatus;
    requested_limit: NiceImportLimit;
    target_count?: (number | null);
    completed_count: number;
    failed_count: number;
    started_by_user_id: string;
    started_at?: (string | null);
    finished_at?: (string | null);
    last_error?: (string | null);
    heartbeat_at?: (string | null);
};

export type NiceImportLimit = '10' | '20' | '50' | 'all';

export type NiceImportStart = {
    limit: 10 | 20 | 50 | 'all';
};

export type limit = 10 | 20 | 50 | 'all';

export type NiceUrlRecommendationRequest = {
    dataset_id?: (number | null);
    url: string;
};

export type PooledCandidate = {
    created_at?: string;
    updated_at?: string;
    id?: (number | null);
    dataset_id: number;
    item_id: number;
    chunk_id: number;
    systems?: Array<(string)>;
    ranks?: {
        [key: string]: unknown;
    };
    is_calibration?: boolean;
    is_trap?: boolean;
    reference_grade?: (number | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RecommendedTask = {
    kind: (AssignmentKind | string);
    eval_type: EvalType;
    dataset_id: number;
    title: string;
    reason: string;
    assignment_id?: (number | null);
    task_id?: (number | null);
};

export type RelevanceReviewPayload = {
    kind?: "relevance";
    dataset: ReviewDataset;
    item: ReviewItem;
    assignment_id: number;
    candidate: PooledCandidate;
    document: DocumentDetail;
    chunk: ChunkSummary;
    allowed_actions?: Array<(string)>;
    item_revision: number;
    existing_submission?: ({
    [key: string]: unknown;
} | null);
};

export type RelevanceReviewSubmit = {
    grade: number;
    confidence?: (JudgmentConfidence | null);
    item_revision: number;
};

export type RetrievalCategory = 'VERBATIM' | 'PARAPHRASE' | 'MULTI_CHUNK' | 'ADVERSARIAL' | 'MULTI_DOCUMENT';

export type RetrievalCreateResponse = {
    id: number;
    dataset_id: number;
    eval_type: EvalType;
    category: RetrievalCategory;
    status: ItemStatus;
    prompt_text: string;
    expected_answer?: (string | null);
    evidence_spans?: Array<EvidenceSpan>;
    trap_evidence_spans?: Array<EvidenceSpan>;
    document_ids?: Array<(number)>;
    item_revision: number;
    validation: ValidationPreview;
};

export type RetrievalReviewPayload = {
    kind?: "retrieval_audit";
    dataset: ReviewDataset;
    item: ReviewItem;
    assignment_id: number;
    documents?: Array<DocumentDetail>;
    chunks?: Array<ChunkSummary>;
    gold_evidence_spans?: Array<EvidenceSpan>;
    trap_evidence_spans?: Array<EvidenceSpan>;
    allowed_actions?: Array<(string)>;
    item_revision: number;
    existing_submission?: ({
    [key: string]: unknown;
} | null);
};

export type RetrievalReviewSubmit = {
    question_validity: 1 | 2 | 3 | 4;
    evidence_quality: 1 | 2 | 3 | 4;
    answer_correctness: 1 | 2 | 3 | 4;
    answer_faithfulness: 1 | 2 | 3 | 4;
    accept_as_gold: boolean;
    notes?: (string | null);
};

export type question_validity = 1 | 2 | 3 | 4;

export type evidence_quality = 1 | 2 | 3 | 4;

export type answer_correctness = 1 | 2 | 3 | 4;

export type answer_faithfulness = 1 | 2 | 3 | 4;

export type ReviewDataset = {
    id: number;
    name: string;
    display_name: string;
    eval_type: EvalType;
};

export type ReviewerKind = 'human' | 'expert';

export type ReviewFact = {
    id: number;
    fact_uuid: string;
    fact_text: string;
    polarity: FactPolarity;
    position: number;
};

export type ReviewItem = {
    id: number;
    dataset_id: number;
    eval_type: EvalType;
    prompt_text: string;
    status: ItemStatus;
    revision: number;
    category?: (RetrievalCategory | null);
    expected_answer?: (string | null);
    why_not_answerable?: (string | null);
};

export type ReviewRubricDimension = {
    key: string;
    label: string;
    options?: Array<(string)>;
};

export type ReviewSubmissionResponse = {
    id: number;
    assignment_id: number;
    item_id: number;
    kind: 'retrieval_audit' | 'relevance';
    completed?: boolean;
};

export type kind2 = 'retrieval_audit' | 'relevance';

export type SignupInviteCreate = {
    role?: UserRole;
    expires_at?: (string | null);
    max_redemptions?: number;
};

export type SignupInviteCreated = {
    role?: UserRole;
    expires_at?: (string | null);
    max_redemptions?: number;
    id: string;
    created_at?: (string | null);
    redeemed_count: number;
    disabled_at?: (string | null);
    created_by_user_id?: (string | null);
    token: string;
};

export type SignupInvitePreview = {
    role: UserRole;
    expires_at?: (string | null);
    remaining_redemptions: number;
};

export type SignupInvitePublic = {
    role?: UserRole;
    expires_at?: (string | null);
    max_redemptions?: number;
    id: string;
    created_at?: (string | null);
    redeemed_count: number;
    disabled_at?: (string | null);
    created_by_user_id?: (string | null);
};

export type SignupInvitesPublic = {
    data: Array<SignupInvitePublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    discord_handle?: (string | null);
    medical_profession?: (string | null);
    role?: UserRole;
    reviewer_kind?: ReviewerKind;
    expertise_note?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    discord_handle?: (string | null);
    medical_profession?: (string | null);
    role?: UserRole;
    reviewer_kind?: ReviewerKind;
    expertise_note?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    invite_token: string;
    email: string;
    password: string;
    full_name?: (string | null);
    discord_handle?: (string | null);
    medical_profession?: (string | null);
};

export type UserRole = 'user' | 'data_admin' | 'admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    discord_handle?: (string | null);
    medical_profession?: (string | null);
    role?: UserRole;
    reviewer_kind?: ReviewerKind;
    expertise_note?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    discord_handle?: (string | null);
    medical_profession?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ValidationPreview = {
    ok: boolean;
    flags?: Array<{
        [key: string]: (string);
    }>;
};

export type AdminReadAdminDatasetsResponse = (Array<DatasetSummary>);

export type AdminCreateAdminDatasetData = {
    requestBody: DatasetCreate;
};

export type AdminCreateAdminDatasetResponse = (DatasetSummary);

export type AdminReadAdminDatasetData = {
    datasetId: number;
};

export type AdminReadAdminDatasetResponse = (DatasetSummary);

export type AdminGenerateDatasetTasksData = {
    datasetId: number;
};

export type AdminGenerateDatasetTasksResponse = (AdminTaskGenerationResult);

export type AdminReadAdminDocumentsResponse = (Array<DocumentSummary>);

export type AdminCreateAdminDocumentData = {
    requestBody: DocumentCreate;
};

export type AdminCreateAdminDocumentResponse = (DocumentDetail);

export type AdminReadAdminDocumentData = {
    documentId: number;
};

export type AdminReadAdminDocumentResponse = (DocumentDetail);

export type AdminToggleAdminDocumentData = {
    documentId: number;
};

export type AdminToggleAdminDocumentResponse = (DocumentSummary);

export type AdminStartNiceImportData = {
    requestBody: NiceImportStart;
};

export type AdminStartNiceImportResponse = (NiceImportJobStatusResponse);

export type AdminReadCurrentNiceImportResponse = ((NiceImportJobStatusResponse | null));

export type AdminCancelNiceImportData = {
    jobId: number;
};

export type AdminCancelNiceImportResponse = (NiceImportJobStatusResponse);

export type AdminReadAdminItemsData = {
    datasetId?: (number | null);
    status?: (ItemStatus | null);
};

export type AdminReadAdminItemsResponse = (Array<AdminItemSummary>);

export type AdminApproveAdminItemData = {
    itemId: number;
    requestBody: AdminModerationAction;
};

export type AdminApproveAdminItemResponse = (AdminItemSummary);

export type AdminRejectAdminItemData = {
    itemId: number;
    requestBody: AdminModerationAction;
};

export type AdminRejectAdminItemResponse = (AdminItemSummary);

export type AdminReadAdminUsersResponse = (unknown);

export type AdminUpdateAdminUserData = {
    userId: string;
};

export type AdminUpdateAdminUserResponse = (unknown);

export type AdminReadAdminUserReviewsData = {
    userId: string;
};

export type AdminReadAdminUserReviewsResponse = (unknown);

export type AdminReadAgreementMetricsData = {
    datasetId?: (number | null);
    reviewerKind?: (ReviewerKind | null);
};

export type AdminReadAgreementMetricsResponse = (Array<AdminAgreementMetric>);

export type AdminReadUserMetricsData = {
    datasetId?: (number | null);
};

export type AdminReadUserMetricsResponse = (Array<AdminUserMetric>);

export type AdminReadInterUserAgreementData = {
    datasetId?: (number | null);
    minOverlap?: number;
};

export type AdminReadInterUserAgreementResponse = (Array<AdminInterUserAgreementMetric>);

export type AdminIngestDatasetResponse = (unknown);

export type AdminExportDatasetData = {
    datasetId?: (number | null);
};

export type AdminExportDatasetResponse = (AdminExport);

export type AuthListInvitesResponse = (SignupInvitesPublic);

export type AuthCreateInviteData = {
    requestBody: SignupInviteCreate;
};

export type AuthCreateInviteResponse = (SignupInviteCreated);

export type AuthPreviewInviteData = {
    token: string;
};

export type AuthPreviewInviteResponse = (SignupInvitePreview);

export type AuthDisableInviteData = {
    inviteId: string;
};

export type AuthDisableInviteResponse = (SignupInvitePublic);

export type AuthInviteSignupData = {
    requestBody: UserRegister;
};

export type AuthInviteSignupResponse = (Token);

export type CreateReadCreateOptionsResponse = (Array<DatasetSummary>);

export type CreateReadSourceDocumentsData = {
    datasetId: number;
    evalType: EvalType;
    includeUsed?: boolean;
};

export type CreateReadSourceDocumentsResponse = (Array<DocumentSummary>);

export type CreateReadSourceDocumentDetailData = {
    datasetId: number;
    documentId: number;
    evalType: EvalType;
};

export type CreateReadSourceDocumentDetailResponse = (DocumentDetail);

export type CreateCreateRetrievalDraftData = {
    requestBody: CreateRetrievalDraftSubmit;
};

export type CreateCreateRetrievalDraftResponse = (RetrievalCreateResponse);

export type CreateSubmitRetrievalDraftData = {
    requestBody: CreateRetrievalDraftSubmit;
};

export type CreateSubmitRetrievalDraftResponse = (RetrievalCreateResponse);

export type CreateCreateFactDecompDraftData = {
    requestBody: CreateFactDecompDraftSubmit;
};

export type CreateCreateFactDecompDraftResponse = (FactDecompCreateResponse);

export type CreateSubmitFactDecompDraftData = {
    requestBody: CreateFactDecompDraftSubmit;
};

export type CreateSubmitFactDecompDraftResponse = (FactDecompCreateResponse);

export type CreateValidateCreationRequestData = {
    requestBody: (CreateRetrievalDraftSubmit | CreateFactDecompDraftSubmit);
};

export type CreateValidateCreationRequestResponse = (ValidationPreview);

export type HomeReadHomeSummaryResponse = (HomeSummary);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NiceFetchNiceRecommendationByUrlData = {
    requestBody: NiceUrlRecommendationRequest;
};

export type NiceFetchNiceRecommendationByUrlResponse = (NiceDocumentResponse);

export type NiceListNiceDownloadsResponse = (Array<NiceDownloadSummary>);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ReviewReadNextReviewTaskData = {
    evalType: EvalType;
    mode?: AssignmentMode;
};

export type ReviewReadNextReviewTaskResponse = (NextReviewRecommendation);

export type ReviewReadRetrievalReviewData = {
    assignmentId: number;
};

export type ReviewReadRetrievalReviewResponse = (RetrievalReviewPayload);

export type ReviewSubmitRetrievalReviewData = {
    assignmentId: number;
    requestBody: RetrievalReviewSubmit;
};

export type ReviewSubmitRetrievalReviewResponse = (ReviewSubmissionResponse);

export type ReviewReadFactDecompReviewData = {
    taskId: number;
};

export type ReviewReadFactDecompReviewResponse = (FactDecompReviewPayload);

export type ReviewSubmitFactDecompReviewData = {
    requestBody: FactDecompReviewSubmit;
    taskId: number;
};

export type ReviewSubmitFactDecompReviewResponse = (FactDecompReviewSubmissionResponse);

export type ReviewReadRelevanceReviewData = {
    assignmentId: number;
};

export type ReviewReadRelevanceReviewResponse = (RelevanceReviewPayload);

export type ReviewSubmitRelevanceReviewData = {
    assignmentId: number;
    requestBody: RelevanceReviewSubmit;
};

export type ReviewSubmitRelevanceReviewResponse = (ReviewSubmissionResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);