FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY --from=oven/bun:1.4.0 /usr/local/bin/bun /usr/local/bin/bun

COPY package.json bun.lock /app/

COPY frontend/package.json /app/frontend/

WORKDIR /app/frontend

RUN bun install --frozen-lockfile

COPY ./frontend /app/frontend

ARG VITE_API_URL
