/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReviewRouteImport } from './routes/_layout/review'
import { Route as LayoutMyWorkRouteImport } from './routes/_layout/my-work'
import { Route as LayoutCreateRouteImport } from './routes/_layout/create'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutReviewRetrievalRouteImport } from './routes/_layout/review.retrieval'
import { Route as LayoutReviewRelevanceRouteImport } from './routes/_layout/review.relevance'
import { Route as LayoutReviewFactDecompositionRouteImport } from './routes/_layout/review.fact-decomposition'
import { Route as LayoutCreateRetrievalRouteImport } from './routes/_layout/create.retrieval'
import { Route as LayoutCreateFactDecompositionRouteImport } from './routes/_layout/create.fact-decomposition'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewRoute = LayoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyWorkRoute = LayoutMyWorkRouteImport.update({
  id: '/my-work',
  path: '/my-work',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateRoute = LayoutCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewRetrievalRoute = LayoutReviewRetrievalRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => LayoutReviewRoute,
} as any)
const LayoutReviewRelevanceRoute = LayoutReviewRelevanceRouteImport.update({
  id: '/relevance',
  path: '/relevance',
  getParentRoute: () => LayoutReviewRoute,
} as any)
const LayoutReviewFactDecompositionRoute =
  LayoutReviewFactDecompositionRouteImport.update({
    id: '/fact-decomposition',
    path: '/fact-decomposition',
    getParentRoute: () => LayoutReviewRoute,
  } as any)
const LayoutCreateRetrievalRoute = LayoutCreateRetrievalRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => LayoutCreateRoute,
} as any)
const LayoutCreateFactDecompositionRoute =
  LayoutCreateFactDecompositionRouteImport.update({
    id: '/fact-decomposition',
    path: '/fact-decomposition',
    getParentRoute: () => LayoutCreateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/create': typeof LayoutCreateRouteWithChildren
  '/my-work': typeof LayoutMyWorkRoute
  '/review': typeof LayoutReviewRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/create/fact-decomposition': typeof LayoutCreateFactDecompositionRoute
  '/create/retrieval': typeof LayoutCreateRetrievalRoute
  '/review/fact-decomposition': typeof LayoutReviewFactDecompositionRoute
  '/review/relevance': typeof LayoutReviewRelevanceRoute
  '/review/retrieval': typeof LayoutReviewRetrievalRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/create': typeof LayoutCreateRouteWithChildren
  '/my-work': typeof LayoutMyWorkRoute
  '/review': typeof LayoutReviewRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/create/fact-decomposition': typeof LayoutCreateFactDecompositionRoute
  '/create/retrieval': typeof LayoutCreateRetrievalRoute
  '/review/fact-decomposition': typeof LayoutReviewFactDecompositionRoute
  '/review/relevance': typeof LayoutReviewRelevanceRoute
  '/review/retrieval': typeof LayoutReviewRetrievalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/create': typeof LayoutCreateRouteWithChildren
  '/_layout/my-work': typeof LayoutMyWorkRoute
  '/_layout/review': typeof LayoutReviewRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/create/fact-decomposition': typeof LayoutCreateFactDecompositionRoute
  '/_layout/create/retrieval': typeof LayoutCreateRetrievalRoute
  '/_layout/review/fact-decomposition': typeof LayoutReviewFactDecompositionRoute
  '/_layout/review/relevance': typeof LayoutReviewRelevanceRoute
  '/_layout/review/retrieval': typeof LayoutReviewRetrievalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/create'
    | '/my-work'
    | '/review'
    | '/settings'
    | '/create/fact-decomposition'
    | '/create/retrieval'
    | '/review/fact-decomposition'
    | '/review/relevance'
    | '/review/retrieval'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/create'
    | '/my-work'
    | '/review'
    | '/settings'
    | '/'
    | '/create/fact-decomposition'
    | '/create/retrieval'
    | '/review/fact-decomposition'
    | '/review/relevance'
    | '/review/retrieval'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/create'
    | '/_layout/my-work'
    | '/_layout/review'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/create/fact-decomposition'
    | '/_layout/create/retrieval'
    | '/_layout/review/fact-decomposition'
    | '/_layout/review/relevance'
    | '/_layout/review/retrieval'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review': {
      id: '/_layout/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof LayoutReviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-work': {
      id: '/_layout/my-work'
      path: '/my-work'
      fullPath: '/my-work'
      preLoaderRoute: typeof LayoutMyWorkRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create': {
      id: '/_layout/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LayoutCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/review/retrieval': {
      id: '/_layout/review/retrieval'
      path: '/retrieval'
      fullPath: '/review/retrieval'
      preLoaderRoute: typeof LayoutReviewRetrievalRouteImport
      parentRoute: typeof LayoutReviewRoute
    }
    '/_layout/review/relevance': {
      id: '/_layout/review/relevance'
      path: '/relevance'
      fullPath: '/review/relevance'
      preLoaderRoute: typeof LayoutReviewRelevanceRouteImport
      parentRoute: typeof LayoutReviewRoute
    }
    '/_layout/review/fact-decomposition': {
      id: '/_layout/review/fact-decomposition'
      path: '/fact-decomposition'
      fullPath: '/review/fact-decomposition'
      preLoaderRoute: typeof LayoutReviewFactDecompositionRouteImport
      parentRoute: typeof LayoutReviewRoute
    }
    '/_layout/create/retrieval': {
      id: '/_layout/create/retrieval'
      path: '/retrieval'
      fullPath: '/create/retrieval'
      preLoaderRoute: typeof LayoutCreateRetrievalRouteImport
      parentRoute: typeof LayoutCreateRoute
    }
    '/_layout/create/fact-decomposition': {
      id: '/_layout/create/fact-decomposition'
      path: '/fact-decomposition'
      fullPath: '/create/fact-decomposition'
      preLoaderRoute: typeof LayoutCreateFactDecompositionRouteImport
      parentRoute: typeof LayoutCreateRoute
    }
  }
}

interface LayoutCreateRouteChildren {
  LayoutCreateFactDecompositionRoute: typeof LayoutCreateFactDecompositionRoute
  LayoutCreateRetrievalRoute: typeof LayoutCreateRetrievalRoute
}

const LayoutCreateRouteChildren: LayoutCreateRouteChildren = {
  LayoutCreateFactDecompositionRoute: LayoutCreateFactDecompositionRoute,
  LayoutCreateRetrievalRoute: LayoutCreateRetrievalRoute,
}

const LayoutCreateRouteWithChildren = LayoutCreateRoute._addFileChildren(
  LayoutCreateRouteChildren,
)

interface LayoutReviewRouteChildren {
  LayoutReviewFactDecompositionRoute: typeof LayoutReviewFactDecompositionRoute
  LayoutReviewRelevanceRoute: typeof LayoutReviewRelevanceRoute
  LayoutReviewRetrievalRoute: typeof LayoutReviewRetrievalRoute
}

const LayoutReviewRouteChildren: LayoutReviewRouteChildren = {
  LayoutReviewFactDecompositionRoute: LayoutReviewFactDecompositionRoute,
  LayoutReviewRelevanceRoute: LayoutReviewRelevanceRoute,
  LayoutReviewRetrievalRoute: LayoutReviewRetrievalRoute,
}

const LayoutReviewRouteWithChildren = LayoutReviewRoute._addFileChildren(
  LayoutReviewRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCreateRoute: typeof LayoutCreateRouteWithChildren
  LayoutMyWorkRoute: typeof LayoutMyWorkRoute
  LayoutReviewRoute: typeof LayoutReviewRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCreateRoute: LayoutCreateRouteWithChildren,
  LayoutMyWorkRoute: LayoutMyWorkRoute,
  LayoutReviewRoute: LayoutReviewRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
